###############################################################################################################
########The functions show below are obtained from the Singular analysis Toolset produced by Fluidigm.
########These functions are used to reading in the Biomark file formats.
########We use these functions for the purpose of reading in our Biomark analysis result generated by our Biomark's system at WIMM only.
########For further downstream analyses, we developed our own pipeline to process the data for our needs.
################################################################################################################
readinCtSingleExp <-function(exp_file,lod){
	exp<-list()
	obj_type <- "EXP"
	exp$obj_type <- as.data.frame(obj_type)
	data_type <- "Ct"
	exp$data_type <- as.data.frame(data_type)
	decimal_mark <- getSeparatorForExpFile(exp_file, "Ct")
	sep <- getBioMarkDelimitor(exp_file)
	num_cols <- max(count.fields(exp_file, sep = sep, quote = "\""))
	data <- read.table(exp_file, skip = 3, fill = T, blank.lines.skip = FALSE, 
			sep = sep, quote = "\"", col.names = 1:num_cols)
	data <- as.matrix(data)
	data_format_identifier <- data[1, 2]
	
	format_string_1 <- "Table Results"
	format_string_2 <- "Heatmap Results"
	
	if (length(grep(format_string_1, data_format_identifier, 
					ignore.case = TRUE)) == 1) {
		data1 <- readRawCtFromTableFormat(data, data_type = data_type,lod=lod, decimal_mark = decimal_mark)
	}else if (length(grep(format_string_2, data_format_identifier, 
					ignore.case = TRUE)) == 1) {
		data1 <- readRawCtFromHeatMapFormat(data, data_type = data_type,lod=lod, decimal_mark = decimal_mark)
	}else {
		stop(paste("input format is unknown qPCR data format: ", data_format_identifier))
	}	
	expression_data <- data1
	exp$org_data <- as.data.frame(expression_data)
	gene_ids <- toupper(rownames(expression_data))
	rownames(exp$org_data)<-gene_ids
	exp$gene_list <- as.data.frame(gene_ids)
	return(exp)
}

getSeparatorForExpFile<-function (file, exp_file_type){
	ret <- "."
	if (exp_file_type == "Linear") {
		sep = ","
		num_cols <- max(count.fields(file, sep = sep, quote = "\""))
		if (num_cols > 5) 
			ret <- ","
	}
	else {
		sep = ";"
		num_cols <- max(count.fields(file, sep = sep, quote = "\""))
		if (num_cols > 5) 
			ret <- ","
	}
	return(ret)
}


getBioMarkDelimitor<-function (file) {
	ds <- getSeparatorForExpFile(file, "Ct")
	if (ds == ".") 
		return(",")
	return(";")
}

readRawCtFromHeatMapFormat<-function (exp, data_type,lod, decimal_mark) {
	quality_row_ind <- which(exp == "Quality Results")
	cols <- exp[8, ]
	ct_start_row <- 10
	empty_line_num <- sum(exp[10:quality_row_ind, 1] == "")
	ct_end_row <- quality_row_ind - empty_line_num - 1
	sample_num = ct_end_row - ct_start_row + 1
	assay_num <- sum(!is.na(as.numeric(cols)))
	data1 <- exp[((ct_start_row - 1):ct_end_row), 2:(assay_num + 
						2)]
	assay_names <- as.vector(data1[1, 2:(assay_num + 1)])
	sample_names <- as.vector(data1[-1, 1])
	uniq_assay_num <- length(as.vector(unique(assay_names)))
	uniq_sample_num <- length(as.vector(unique(sample_names)))
	if (uniq_sample_num != length(sample_names)) 
		stop("duplicate sample are not supported.")
	data1 <- data1[-1, -1]
	if (decimal_mark == ",") {
		data1 <- itn_replaceCommaWithPeriod(data1, 2)
	}
	data1 <- apply(data1, 2, as.numeric)
	data1_quality <- exp[(quality_row_ind + 3):(quality_row_ind + 
						2 + sample_num), 3:(assay_num + 2)]
	data1[data1_quality == "Fail" & data1 < 999] <- 999
	data1 <- t(data1)
	colnames(data1) <- sample_names
	if (uniq_assay_num < assay_num) {
		data1 <- getUnqiueGeneExp(data = data1, gene_ids = assay_names, 
				lod = lod, data_type = data_type)
	}
	else {
		rownames(data1) <- assay_names
	}
	data1 <- as.data.frame(data1)
	return(data1)
}

readRawCtFromTableFormat<-function (exp,data_type,lod,decimal_mark) {
	rownum <- length(exp[, 1])
	row1 <- exp[8, ]
	row2 <- exp[9, ]
	row12 <- paste(row1, row2, sep = ":")
	uid_col <- 1
	sample_col <- which(row12 == "Sample:Name")
	assay_col <- (which(row2 == "Name"))[2]
	ct_value_col <- which(row12 == "Ct:Value")
	ct_call_col <- which(row12 == "Ct:Call")
	data1 <- exp[10:rownum, c(uid_col, sample_col, assay_col, 
					ct_value_col, ct_call_col)]
	data1_c1 <- unlist(strsplit(data1[, 1], "-"))
	data1_samples <- data1_c1[seq(1, length(data1_c1), 2)]
	data1_assays <- data1_c1[seq(2, length(data1_c1), 2)]
	data1_ct <- data1[, 4]
	if (decimal_mark == ",") {
		data1_ct <- itn_replaceCommaWithPeriod1D(data1_ct)
	}
	data1_quality <- data1[, 5]
	data1_ct[data1_quality == "Fail" & as.numeric(data1_ct) < 999] <- 999
	data1[, 4] <- data1_ct
	unique_data1_samples <- as.vector(unique(data1_samples))
	unique_data1_assays <- as.vector(unique(data1_assays))
	data2 <- matrix(NA, nr = length(unique_data1_samples), nc = length(unique_data1_assays))
	colnames(data2) <- unique_data1_assays
	rownames(data2) <- unique_data1_samples
	sample_names <- matrix(NA, nr = length(unique_data1_samples), 
			nc = 1)
	assay_names <- matrix(NA, nr = length(unique_data1_assays), 
			nc = 1)
	rownames(sample_names) <- unique_data1_samples
	rownames(assay_names) <- unique_data1_assays
	for (i in 1:nrow(data1)) {
		uid <- unlist(strsplit(data1[i, 1], "-"))
		rowname <- uid[1]
		colname <- uid[2]
		data2[rowname, colname] <- data1[i, 4]
		sample_names[rowname, 1] <- data1[i, 2]
		assay_names[colname, 1] <- data1[i, 3]
	}
	sample_names <- as.vector(sample_names)
	assay_names <- as.vector(assay_names)
	if (decimal_mark == ",") {
		data2 <- itn_replaceCommaWithPeriod(data2, 2)
	}
	data2 <- apply(data2, 2, as.numeric)
	data2 <- t(data2)
	uniq_assay_num <- length(as.vector(unique(assay_names)))
	uniq_sample_num <- length(as.vector(unique(sample_names)))
	if (uniq_assay_num != length(assay_names) || uniq_sample_num != 
			length(sample_names)) 
		stop("Duplicate sample or assay are not supported for table format")
	data2_col_num <- length(data2[1, ])
	data2_row_num <- length(data2[, 1])
	if (uniq_sample_num < data2_col_num) {
		stop("EXP data contains duplicate samples")
	}
	colnames(data2) <- as.vector(sample_names)
	if (uniq_assay_num < data2_row_num) {
		data2 <- getUnqiueGeneExp(data = data2, gene_ids = as.vector(assay_names),lod)
	}
	else {
		rownames(data2) <- assay_names
	}
	return(data2)
}

getUnqiueGeneExp<-function (data, gene_ids, lod, data_type = "LinearExp"){
	gene_nums <- length(gene_ids)
	gene_ids_repeated <- gene_ids[duplicated(gene_ids)]
	index_repeated_genes <- c(1:length(gene_ids))[gene_ids %in% 
					gene_ids_repeated]
	if (length(index_repeated_genes) == 0) {
		return(data)
	}
	cat("\nThe following genes are replicated, and their expression values will be averaged.\n")
	for (i in 1:length(gene_ids_repeated)) cat(paste("     ", 
						gene_ids_repeated[i], "\n", sep = ""))
	flush.console()
	data_unique <- data[-index_repeated_genes, ]
	data <- data[index_repeated_genes, ]
	gene_ids_unique <- gene_ids[-index_repeated_genes]
	gene_ids <- gene_ids[index_repeated_genes]
	gene_nums <- length(gene_ids)
	exp_data <- c()
	used <- c()
	unique_gene_ids <- c()
	for (i in 1:gene_nums) {
		gene_name <- gene_ids[i]
		unique_gene_pos <- c(1:gene_nums)[gene_ids == gene_name]
		if (match(i, used, nomatch = 0) == 0) {
			unique_gene_ids <- c(unique_gene_ids, gene_name)
			duplicate_exp_data <- data[unique_gene_pos, ]
			duplicate_exp_data[duplicate_exp_data == -1] <- lod
			if (data_type == "LinearExp") {
				i_exp_data <- apply(duplicate_exp_data, 2, mean)
			}
			else {
				duplicate_exp_data <- 2^(-duplicate_exp_data)
				i_exp_data <- apply(duplicate_exp_data, 2, mean)
				i_exp_data <- -1 * log2(i_exp_data)
			}
			exp_data <- rbind(exp_data, i_exp_data)
		}
		used <- c(used, unique_gene_pos)
	}
	exp_data <- rbind(data_unique, exp_data)
	rownames(exp_data) <- c(gene_ids_unique, as.vector(unique_gene_ids))
	return(exp_data)
}
